name: CI - Build, Test, Coverage, SonarCloud

on:
  push:
    branches: [ "main", "master", "**" ]
  pull_request:
    branches: [ "main", "master", "**" ]

jobs:
  build-test-sonar:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Run Tests with Coverage
      run: dotnet test --configuration Release --collect "XPlat Code Coverage"

    - name: Locate coverage file
      id: coverage
      run: |
        file=$(find . -type f -name "coverage.cobertura.xml")
        echo "coverage_path=$file" >> $GITHUB_OUTPUT

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v2
      with:
        args: >
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
          -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.cs.opencover.reportsPaths=**/coverage.cobertura.xml
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    - name: Upload Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: ${{ steps.coverage.outputs.coverage_path }}

    - name: Vulnerability Scan
      run: dotnet list package --vulnerable || true
